-- MySQL Script generated by MySQL Workbench
-- sex 12 mar 2021 14:52:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ancine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ancine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ancine` ;
USE `ancine` ;

-- -----------------------------------------------------
-- Table `ancine`.`diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`diretor` (
  `registro` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `naturalidade_diretor` VARCHAR(45) NULL,
  PRIMARY KEY (`registro`),
  UNIQUE INDEX `registrodiretor_UNIQUE` (`registro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ancine`.`produtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`produtor` (
  `registro` INT NOT NULL,
  `cnpj` VARCHAR(14) NULL,
  `pais_origem` VARCHAR(45) NULL,
  `razao_social` VARCHAR(45) NULL,
  PRIMARY KEY (`registro`),
  UNIQUE INDEX `registro_produtor_UNIQUE` (`registro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ancine`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`filme` (
  `cpb` INT NOT NULL,
  `ano` INT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `org_temporal` VARCHAR(45) BINARY NULL DEFAULT 'nao seriado',
  `tipo_obra` VARCHAR(45) NULL DEFAULT 'nao classificada',
  `data_cpb` DATETIME NULL,
  `qtd_episodios` INT NULL DEFAULT NULL,
  `produtor_registro` INT NOT NULL,
  `diretor_registro` INT NOT NULL,
  PRIMARY KEY (`cpb`, `produtor_registro`, `diretor_registro`),
  INDEX `fk_filme_produtor_idx` (`produtor_registro` ASC) VISIBLE,
  INDEX `fk_filme_diretor1_idx` (`diretor_registro` ASC) VISIBLE,
  CONSTRAINT `fk_filme_produtor`
    FOREIGN KEY (`produtor_registro`)
    REFERENCES `ancine`.`produtor` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_diretor1`
    FOREIGN KEY (`diretor_registro`)
    REFERENCES `ancine`.`diretor` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ancine`.`complexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`complexo` (
  `registro` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`registro`),
  UNIQUE INDEX `registro_UNIQUE` (`registro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ancine`.`exibidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`exibidor` (
  `registro` INT NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`registro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ancine`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`sala` (
  `registro` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `qtd_assentos` INT NULL,
  `situacao_regular` INT NULL,
  `complexo_registro` INT NOT NULL,
  `exibidor_registro` INT NOT NULL,
  PRIMARY KEY (`registro`, `complexo_registro`, `exibidor_registro`),
  UNIQUE INDEX `registro_sala_UNIQUE` (`registro` ASC) VISIBLE,
  INDEX `fk_sala_complexo1_idx` (`complexo_registro` ASC) VISIBLE,
  INDEX `fk_sala_exibidor1_idx` (`exibidor_registro` ASC) VISIBLE,
  CONSTRAINT `fk_sala_complexo1`
    FOREIGN KEY (`complexo_registro`)
    REFERENCES `ancine`.`complexo` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sala_exibidor1`
    FOREIGN KEY (`exibidor_registro`)
    REFERENCES `ancine`.`exibidor` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ancine`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`municipio` (
  `codigo_ibge` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_ibge`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `ancine`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`sessao` (
  `filme_cpb` INT NOT NULL,
  `sala_registro` INT NOT NULL,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  PRIMARY KEY (`filme_cpb`, `sala_registro`),
  INDEX `fk_filme_has_sala_sala1_idx` (`sala_registro` ASC) VISIBLE,
  INDEX `fk_filme_has_sala_filme1_idx` (`filme_cpb` ASC) VISIBLE,
  CONSTRAINT `fk_filme_has_sala_filme1`
    FOREIGN KEY (`filme_cpb`)
    REFERENCES `ancine`.`filme` (`cpb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_sala_sala1`
    FOREIGN KEY (`sala_registro`)
    REFERENCES `ancine`.`sala` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ancine`.`complexo_em_municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ancine`.`complexo_em_municipio` (
  `municipio_codigo_ibge` INT NOT NULL,
  `complexo_registro` INT NOT NULL,
  PRIMARY KEY (`municipio_codigo_ibge`, `complexo_registro`),
  INDEX `fk_municipio_has_complexo_complexo1_idx` (`complexo_registro` ASC) VISIBLE,
  INDEX `fk_municipio_has_complexo_municipio1_idx` (`municipio_codigo_ibge` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_has_complexo_municipio1`
    FOREIGN KEY (`municipio_codigo_ibge`)
    REFERENCES `ancine`.`municipio` (`codigo_ibge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_municipio_has_complexo_complexo1`
    FOREIGN KEY (`complexo_registro`)
    REFERENCES `ancine`.`complexo` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
